// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxymksodoqyjoiyemxtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eW1rc29kb3F5am9peWVteHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDkwNDgsImV4cCI6MjA2MDQ4NTA0OH0.AHKHdr10zH7nqhxPuJ71ecNzG0yzSEL46soDanc36rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);